#include "PHOENIX_Infantry_Base.hpp"
#include "PHOENIX_Infantry_Unarmed.hpp"
#include "PHOENIX_Infantry_Rifleman.hpp"
#include "PHOENIX_Infantry_Grenadier.hpp"
#include "PHOENIX_Infantry_Autorifleman.hpp"
#include "PHOENIX_Infantry_Marksman.hpp"